import * as formatter from "./formatter.js";
declare const apiVersion = "0.3.0";
declare const ERROR_VERIFICATION_STATUS = "ERROR";
declare const dict2Leaves: (obj: any) => any[];
declare function getHashSum(content: string): any;
declare function sha256Hasher(data: string): any;
declare const getFileHashSum: (filename: any) => any;
declare function readExportFile(filename: any): Promise<any>;
declare function generateVerifyPage(verificationHashes: any, aquaObject: any, verbose: boolean | undefined, doVerifyMerkleProof: boolean): AsyncGenerator<{}, void, unknown>;
declare function verifyPage(input: any, verbose: any, doVerifyMerkleProof: any): Promise<any[]>;
declare function checkAPIVersionCompatibility(server: any): Promise<any[]>;
export { generateVerifyPage, verifyPage, apiVersion, ERROR_VERIFICATION_STATUS, dict2Leaves, getHashSum, sha256Hasher, getFileHashSum, formatter, checkAPIVersionCompatibility, readExportFile, };
